window.PROJECT_SIA_SEED = {
  meta: {
    companyName: 'CV Contoh SIA',
    periodLabel: 'April 2026',
    sourceNote: 'Workbook asli dipakai sebagai referensi struktur akun, lalu dikembangkan menjadi web app interaktif.'
  },
  accounts: [
    { code: '1101', name: 'Kas', bucket: 'asset_current' },
    { code: '1108', name: 'Bank', bucket: 'asset_current' },
    { code: '1102', name: 'Piutang dagang', bucket: 'asset_current' },
    { code: '1103', name: 'Asuransi dibayar dimuka', bucket: 'asset_current' },
    { code: '1104', name: 'Iklan dibayar dimuka', bucket: 'asset_current' },
    { code: '1105', name: 'Perlengkapan kantor', bucket: 'asset_current' },
    { code: '1106', name: 'Persediaan barang dagang', bucket: 'asset_current' },
    { code: '1107', name: 'Peralatan operasional', bucket: 'asset_fixed' },
    { code: '1110', name: 'PPN Masukan', bucket: 'asset_current' },
    { code: '1202', name: 'Gedung', bucket: 'asset_fixed' },
    { code: '1203', name: 'Akumulasi penyusutan gedung', bucket: 'contra_asset' },
    { code: '2101', name: 'Utang usaha', bucket: 'liability_current' },
    { code: '2103', name: 'Utang gaji dan komisi', bucket: 'liability_current' },
    { code: '2110', name: 'PPN Keluaran', bucket: 'liability_current' },
    { code: '3101', name: 'Modal Tiara', bucket: 'equity_capital' },
    { code: '3102', name: 'Prive Tiara', bucket: 'equity_withdrawal' },
    { code: '4101', name: 'Pendapatan jasa', bucket: 'revenue' },
    { code: '4102', name: 'Penjualan barang dagang', bucket: 'revenue' },
    { code: '5101', name: 'Biaya gaji dan komisi', bucket: 'expense' },
    { code: '5110', name: 'Harga Pokok Penjualan', bucket: 'expense' },
    { code: '5102', name: 'Biaya sewa', bucket: 'expense' },
    { code: '5103', name: 'Biaya iklan', bucket: 'expense' },
    { code: '5105', name: 'Biaya lainnya', bucket: 'expense' },
    { code: '5106', name: 'Biaya perlengkapan kantor', bucket: 'expense' },
    { code: '5107', name: 'Biaya penyusutan gedung', bucket: 'expense' },
    { code: '5108', name: 'Biaya asuransi', bucket: 'expense' }
  ],
  openingBalances: [
    { code: '1101', debit: 18000000, credit: 0 },
    { code: '1108', debit: 0, credit: 0 },
    { code: '1102', debit: 4000000, credit: 0 },
    { code: '1103', debit: 1200000, credit: 0 },
    { code: '1104', debit: 0, credit: 0 },
    { code: '1105', debit: 800000, credit: 0 },
    { code: '1106', debit: 780000, credit: 0 },
    { code: '1107', debit: 0, credit: 0 },
    { code: '1110', debit: 0, credit: 0 },
    { code: '1202', debit: 12000000, credit: 0 },
    { code: '1203', debit: 0, credit: 1200000 },
    { code: '2101', debit: 0, credit: 3000000 },
    { code: '2103', debit: 0, credit: 0 },
    { code: '2110', debit: 0, credit: 0 },
    { code: '3101', debit: 0, credit: 32580000 },
    { code: '3102', debit: 0, credit: 0 },
    { code: '4101', debit: 0, credit: 0 },
    { code: '4102', debit: 0, credit: 0 },
    { code: '5101', debit: 0, credit: 0 },
    { code: '5110', debit: 0, credit: 0 },
    { code: '5102', debit: 0, credit: 0 },
    { code: '5103', debit: 0, credit: 0 },
    { code: '5105', debit: 0, credit: 0 },
    { code: '5106', debit: 0, credit: 0 },
    { code: '5107', debit: 0, credit: 0 },
    { code: '5108', debit: 0, credit: 0 }
  ],
  demoTransactions: [
    {
      id: 'tx-demo-1',
      mode: 'template',
      type: 'service_revenue_cash',
      date: '2026-04-01',
      description: 'Pendapatan jasa tunai dari klien A',
      amount: 8500000,
      account: '4101',
      source: '1101'
    },
    {
      id: 'tx-demo-2',
      mode: 'template',
      type: 'service_revenue_credit',
      date: '2026-04-03',
      description: 'Jasa selesai dan ditagihkan ke klien B',
      amount: 5000000,
      account: '4101',
      source: '1102'
    },
    {
      id: 'tx-demo-3',
      mode: 'template',
      type: 'expense_cash',
      date: '2026-04-05',
      description: 'Pembayaran gaji staf mingguan',
      amount: 3000000,
      account: '5101',
      source: '1101'
    },
    {
      id: 'tx-demo-4',
      mode: 'template',
      type: 'expense_cash',
      date: '2026-04-06',
      description: 'Bayar sewa kantor bulanan',
      amount: 1500000,
      account: '5102',
      source: '1101'
    },
    {
      id: 'tx-demo-5',
      mode: 'template',
      type: 'collect_receivable',
      date: '2026-04-08',
      description: 'Penerimaan pelunasan piutang klien lama',
      amount: 2500000,
      account: '1102',
      source: '1101'
    },
    {
      id: 'tx-demo-6',
      mode: 'template',
      type: 'buy_supplies',
      date: '2026-04-10',
      description: 'Membeli perlengkapan kantor secara kredit',
      amount: 650000,
      account: '1105',
      source: '2101'
    },
    {
      id: 'tx-demo-7',
      mode: 'template',
      type: 'owner_draw',
      date: '2026-04-12',
      description: 'Pengambilan pribadi pemilik',
      amount: 750000,
      account: '3102',
      source: '1101'
    },
    {
      id: 'tx-demo-8',
      mode: 'template',
      type: 'insurance_adjustment',
      date: '2026-04-30',
      description: 'Penyesuaian beban asuransi akhir bulan',
      amount: 200000,
      account: '5108',
      source: '1103'
    },
    {
      id: 'tx-demo-9',
      mode: 'template',
      type: 'depreciation_adjustment',
      date: '2026-04-30',
      description: 'Penyesuaian penyusutan gedung',
      amount: 250000,
      account: '5107',
      source: '1203'
    }
  ]
};
